# Dados de conexão ao MySQL na Nuvem (Aiven)
spring.datasource.url=jdbc:mysql://mysql-rentacar-azunie.h.aivencloud.com:24509/defaultdb?useSSL=true&allowPublicKeyRetrieval=true&ssl-mode=REQUIRED&serverTimezone=UTC
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_RSso2RGc1OiQYxa2qgC


#debug=true

# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false
