# Dados de conexão ao MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/stand_automovel
spring.datasource.username=root
spring.datasource.password=""

# Configurações do Thymeleaf (para veres as mudanças no HTML sem reiniciar o servidor)
spring.thymeleaf.cache=false

# Para o Spring não tentar criar tabelas sozinho (tu já as criaste no MySQL)
spring.jpa.hibernate.ddl-auto=none